### ISSUE TITLE
Data Team: Back End Server Options

### ISSUE THREAD

**Issue by rscottlundgren** [codeforboston/jobhopper#12]
We should start thinking about which back end server platform we should start off with. Initial options we discussed were:

- AWS
- Google
- Heroku

Would need someone to do research on top five options available and do a "pro/con" list.

**Comment by jedpittman** [comment]
Azure
and plain web hosting are worth considering. 

The following are links that are potentially worth reviewing and show the costs are generally going to be in the 5-20$/month range. 

https://www.hostingadvice.com/how-to/aws-azure-google-cloud-alternatives/#:~:text=AWS%20prices%20start%20around%20%2430,%24100%20per%20month%20per%20user.

For Infrastructure as a Service (IaaS), that is, where the server itself is configured and run as a layer of software so that it can be easily maintained/upgraded, Gartner has a magic quadrant that describes AWS at the top: 
https://www.gartner.com/doc/reprints?id=1-1CMAPXNO&ct=190709&st=sb

To Do a good pro/con list, I think that we need to have a better idea of our data/app requirements. Here's a series of follow up questions to start:
1. Do we plan to maintain any kind of accounts on users in the application?
2. Do we plan to build an ongoing refresh of data pulled from sites like BLS ? 
3. What data store do we plan to use and how do we expect to organize it? (Simple static JSON or something else?)
4. What data do we want to log for debugging?
5. What data do we want to track as the application is used?

**Comment by jedpittman** [comment]
@rscottlundgren @AnnieLa can we discuss this issue next week and summarize the discussion/results here? This kind of information will help us push this issue along and start thinking about the issue @EndyPremier  brought up last night about starting to think about deployment of this project. I know it is still a bit far off, but getting a few decisions written down would be a good start.

**Comment by jedpittman** [comment]
Created a new, clean issue for this with AnnieLa that is more focused on partnerships etc.
