### ISSUE TITLE
Requirements: Hard Skill Data Points (Lillian)

### ISSUE THREAD

**Issue by rscottlundgren** [codeforboston/jobhopper#18]
O*Net API: [https://services.onetcenter.org/reference/](https://services.onetcenter.org/reference/)
BLS API: [https://www.bls.gov/developers/](https://www.bls.gov/developers/)

3. How do we get education/skills and wages/wage ranges for jobs?

**Comment by gschubert** [comment]
Wage series can be pulled through the BLS API or as a static data set from the BLS website by manual pull. Relevant tables are from the OES and can be pulled via a series identifier that looks like this:
![image](https://user-images.githubusercontent.com/35321293/88113473-d864ef00-cb7f-11ea-8d8e-0924f664f528.png)
Manual wage table source would be this - has wage and employment data by SOC at an MSA level
https://www.bls.gov/oes/tables.htm

**Comment by jedpittman** [comment]
Skills already handled as part of #16 see below: 
https://services.onetcenter.org/ws/mnm/careers/[O*NET-SOC Code]/skills
https://services.onetcenter.org/reference/mnm/career/skills

**Comment by jedpittman** [comment]
Scroll down for visualizations https://datausa.io/profile/soc/elementary-middle-school-teachers

**Comment by jedpittman** [comment]
http://dataatwork.org/ Seems to have a good ml library as well for saving information

**Comment by rscottlundgren** [comment]
Educational attainment for workers 25 years and older by detailed occupation -> https://www.bls.gov/emp/tables/educational-attainment.htm

Job Zone -> https://www.onetonline.org/help/online/zones#:~:text=The%20five%20Job%20Zones%20are,occupations%20that%20need%20considerable%20preparation
Job Zone Specifics -> https://www.onetonline.org/find/zone?z=4&g=Go
*CAVEAT* This information is helpful for providing more specific context/color

Web Scrape Indeed API for Skills Data -> https://opensource.indeedeng.io/api-documentation/docs/job-search/
[Endy + Jed -> Interest in/Experience with Web Scraping]
Web Scrape Monster API for Skills Data -> https://partner.monster.com/job-search

DataWheel -> https://datausa.io/profile/soc/elementary-middle-school-teachers
DataAtWork -> http://dataatwork.org/

ONET ->
- Skills -> https://services.onetcenter.org/reference/mnm/career/skills
- Technology -> https://services.onetcenter.org/reference/mnm/career/technology
- Education -> https://services.onetcenter.org/reference/mnm/career/education

Open Skills API -> https://github.com/workforce-data-initiative/skills-api

**Comment by jedpittman** [comment]
@rscottlundgren , can we assign this to @l-cheung ? At this point I think the next step is to get the script that Lillian has into the flow so that folks can load this data to hydrate one or more db tables in the sqlite db, depending on how far Lillian wants to take this, it could be integrated into the flow while closing this issue (see #22 ) for what we did to setup loading the data, or a new issue could be created to do that.

**Comment by l-cheung** [comment]
Happy to work on this. Drafted Python scraping utils to download BLS OES data from https://www.bls.gov/oes/tables.htm. That seems like an easier path forwards than using the series IDs when it comes to OES data.

**Comment by l-cheung** [comment]
**In Progress**
* Drafted a process to scrape and download BLS wage/employment data into a local SQLite database. The dataset is the latest from BLS, keyed by SOC code, at https://www.bls.gov/oes/tables.htm 
* There are a lot of Series IDs for the BLS data, with each series ID corresponding to a single occupation and location's wage/employment data. Programmatically pulling all the data is more efficient.

**Remaining for MVP**
* Need a table for SOC codes linking to O*Net pages. Links seem to be of the format www.onetonline.org/link/summary/<SOC Code>
* This needs to go into a local Postgres database for testing
* There are SOC codes from the O*Net transitions data that do not exist in the latest BLS dataset. We should account for those. 
* Eventually, load this into a hosted Postgres database. 

**Extras - Beyond MVP**
* Indeed scraping, or any data pulls beyond having the transitions data + BLS wage/employment data

**Comment by jedpittman** [comment]
Can you create a couple of tickets for this work?
1. Scripts to create the table in postgres and load it with the SOC code and any 'overrides' to the url that need to be handled. (We're handling the base case as a simple javascript function in issue #52 
2. A second ticket to migrate the scraping process to work to load the data from BLS into postgres instead of sql lite? 
You can then assign yourself whichever of these you want to do more and then close this ticket out. 
Once we get through the main parts of the sprint, I think we'll have time to talk about how to load/get the rest of the data in.

Thanks for writing back.

**Comment by l-cheung** [comment]
Sure. Created two tickets for those tasks. Planning to tackle the loading into a local Postgres DB first, since that logically comes before editing SOC code URL overrides in the DB. I'll close this ticket and keep the other two in mind for documentation.
