### ISSUE TITLE
Disable state selection until occupation is selected

### ISSUE THREAD

**Issue by alexjball** [codeforboston/jobhopper#219]
Disable state selection until occupation is selected

**Comment by jedpittman** [comment]
on a separate note, I've spent a little time on this item #219  which is about disabling the state dropdown until occupation is picked.
My instinct is to have isLoading=True unless or isDisabled=True until there is something in the first dropdown. My goal right now is to use the redux store and find out if state.selectedOccupation is populated....and flip one of the flags based on that...but I've not done thunks before and don't really recognize the patterns we're using and I want to implement in a way that would be consistent.
Is it pretty standard stuff if I read up on thunks or is there some guidance you have on best way to handle?




From slack re: code changes
Alex Ball  2:34 PM
"...you can use the useOccupationsState hook to access the currently selected occupation in the StateSelectContainer: const { selectedOccupation } = useOccupationsState();.
...
Since we set isDisabled based on loading and error, it might make sense to add a disabled prop so you can set that based on any of the three props"

**Comment by jedpittman** [comment]
tests passed locally:
Tests:       16 passed, 16 total
Snapshots:   0 total
Time:        10.66s
Ran all test suites.
