### ISSUE TITLE
Pending Update: Two fixes needed to documentation

### ISSUE THREAD

**Issue by jkoren** [codeforboston/jobhopper#322]
Need to fix this link in References.md:chrome-extension://cbnaodkpfinfiipjblikofhlhlcickei/src/pdfviewer/web/viewer.html?file=https://scholar.harvard.edu/files/stansbury/files/schubertstansburytaskamain_0.pdf 

This file can be removed, as the data is included in the installation.md: DjangoData.md

**Comment by jedpittman** [comment]
@jkoren , Jeff, it looks like the pull request you submitted actually includes files/code changes that are not part of the documentation. Can you either close this pull request or update the branch so that we're not changing the files that are not ending in .md ? 
If you need help with it from the git side, you can feel free to reach out. 
Thanks!

**Comment by jkoren** [comment]
@jedpittman for some reason, this pull request included the changes I made in [this pull request](https://github.com/codeforboston/jobhopper/pull/318).  I will close this pull request and create another.

**Comment by jkoren** [comment]
created a new pull request.  closing this one.
