### ISSUE TITLE
Text and Layout Changes

### ISSUE THREAD

**Issue by jedpittman** [codeforboston/jobhopper#338]
Ensure that the latest changes from @sashamaryl  are integrated and that you're getting the last code from develop before starting since some of these may not be needed.

Fix the items below:
1. Change results sentence, remove wage source (we mean the state. The state should not be in the results themselves.)
2. Space between “Transition Share:” and percentage must match space between “Salary:” and “Hourly”
3. Footnote text (reviewed by AS):  The Treemap above shows the occupations which Marketing Managers move to when they change occupation based on the (show number if possible, ie 10,000) observations in our dataset. The transition share is the percentage of these observed Marketing Managers who have moved into each of the occupations listed.
4. Align left to Treemap edge, match text size of “What do xxx transitions to?” 

For Review, please have Alex or Jed review the changes. Reach out them in slack and leave a note in the comments. Once someone reviews, make a comment in the ticket that this looks good and is approved. Another team member will then merge.

A good review will:
Ensure all bullets are done.
Only files/changes to files are related to the changes described.
Ensure the code runs on your machine locally and works as expected.
Ensure that the tests run on your machine locally
There are no unresolved conflicts/errors with tests for the merge request.

**Comment by edward-malouf** [comment]
PDF with a visual key to the above punchlist 
[Table data layout.pdf](https://github.com/codeforboston/jobhopper/files/6112251/Table.data.layout.pdf)

**Comment by jkoren** [comment]
For item 2 -  Space between “Transition Share:” and percentage must match space between “Salary:” and “Hourly”

The space between "Transition Share" and the Percentage seems to match the PDF Visual Key.  Does any more need to be done?
![image](https://user-images.githubusercontent.com/67333843/110842758-86d7b480-8275-11eb-990c-0027e39c1086.png)

**Comment by edward-malouf** [comment]
Jeff,

This issue regarding the Treemap, note the table. See the PDF of the google doc and visual key attached.

The table has one issue, the state must appear in the lower left corner and be taken out of the results sentence.

I am here to answer any question and to help decide what is required for our MVP.

Thanks!

Ed




Content • Design Collaborative LLC 
433 Country Way
Scituate, MA 02066
781-378-1484  

Bonding over wallpaper
http://contentdesign.me/historical-finishes/

**Comment by edward-malouf** [comment]
I just noticed the visual key and text do not match.

Let me fix this.

Ed


UX/UI 
http://edmalouf.me/

Content•Design
http://contentdesign.me/

**Comment by edward-malouf** [comment]
Up to date visual reference to the google doc.

**Comment by jkoren** [comment]
Hi Ed, 
I completed items #1 and #3.  In #3 I will look to see if there is a straightforward way to include the number of observations.

#2 - Thanks for the note that this refers to the Treemap.  I understand we want an additional space between the "Transition Share" and the percentage in the text line under the Treetable, so I added that.

#4 - The “What do xxx transitions to?” table and the Treemap text size is different because for the table, the the text is a title in a Material-UI table and the in the Treemap the text is an HTML title.  Let me see  if I can fix that.

As an aside, I'm not sure if there is a connection between the letters on the visual reference and the item numbers on the google doc?

Reach out to me at 617-590-0528 if I got anything wrong!

**Comment by jkoren** [comment]
@jedpittman a test failed when I ran `npm test` because the test is still looking for the state.  Let me know if I should update the test.
```
       99 |     await selectEvent.select(getByLabelText('state-select'), 'California');
      100 | 
    > 101 |     await waitFor(() =>
          |           ^
      102 |       expect(getByText(/in California/i)).toBeInTheDocument()
      103 |     );
      104 | 
```

**Comment by edward-malouf** [comment]
Thanks Jeff!

#4 is just the type of refinement that is NOT required for MVP.

Ed


Content • Design Collaborative LLC
433 Country Way
Scituate, MA 02066
781-378-1484 
 
Mills Along the Blackstone
http://contentdesign.me/20-years-along-blackstone-river/

**Comment by jedpittman** [comment]
> @jedpittman a test failed when I ran `npm test` because the test is still looking for the state. Let me know if I should update the test.
> 
> ```
>        99 |     await selectEvent.select(getByLabelText('state-select'), 'California');
>       100 | 
>     > 101 |     await waitFor(() =>
>           |           ^
>       102 |       expect(getByText(/in California/i)).toBeInTheDocument()
>       103 |     );
>       104 | 
> ```

Yes, the tests should all be in a working state prior to check-in/merge request.
If any tests start to fail as a result of the changes to the code; they should be updated.
Also if new changes are added to the code, that is the correct time to add tests to make sure we have coverage for new code.

**Comment by jkoren** [comment]
Tests passed.  Pushed and created reviews and pull request.
We considered adding clarifying language to the titles as below, but decided to hold off because this is covered in the Tool Tip.
![image](https://user-images.githubusercontent.com/67333843/111399541-f4cc1380-869b-11eb-8ab3-607118266a98.png)
![image](https://user-images.githubusercontent.com/67333843/111399598-10371e80-869c-11eb-9405-6e6538ef68b0.png)
