### ISSUE TITLE
Data Team: Research Visualization Tools

### ISSUE THREAD

**Issue by rscottlundgren** [codeforboston/jobhopper#5]
Research Data Visualization Tool options - Pro/Con List

Temporarily Assigned To: Melissa Luna

**Comment by MRLmic** [comment]
I looked into Tableau Public, D3.js, and PowerBI but ultimately decided to compare Tableau Public and D3.js since they both seem like good choices depending on what dev strategy we decide to take. If anyone has any other questions re these choices and what features we may need, let me know and I'd be happy to keep looking into it.

Tableau Public | D3.js | Feature
-- | -- | --
Free with   limitations      - limited up to 10 million rows   -cannot connect to   Db, only used with excel or csv files   -all work   published for public automatically | Free | Cost
Easy ramp up     Good for data exploration | -Known to be more   difficult   -Not good for data   exploration (would need to start with a plan) | Ramp Up Difficulty
Automatically produces         mobile versions | Would need to build | Mobile   Compatibility
Limited customizations | Highly customizable (but         would need to start from scratch) | Customizability
Doesn't require DB hit for         every query so fast loading times |   | Other?

**Comment by MRLmic** [comment]
Qualifications for non-profits requesting free full Tableau use:
![image](https://user-images.githubusercontent.com/30061432/82133126-c55b2a80-979c-11ea-912a-9455960b738d.png)

**Comment by rscottlundgren** [comment]
Thank you, Luna! If you come across anything else in your travels between now and Tuesday, please feel free to continue adding whatever information you find here. Stay safe!

**Comment by carollieb** [comment]
Currently, it appears that D3 is our data visualization of choice, but that may change.
