### ISSUE TITLE
Create a JS Function for returning the correct onet location

### ISSUE THREAD

**Issue by jedpittman** [codeforboston/jobhopper#52]
Background:
When a user clicks a location on a tree-map, it should bring us to the location in onet described for that SOC code.

- [ ] Review the slide deck provided by Anna for requirements
- [ ] Create an account on codePen if not available already. 
- [ ] Create a code pen that writes a function getOnetUrl(socCodeInput, isOnline) and returns a string url for the correct onet location` if isOnline === true, else returns a static string that depends on the socCodeInput`; this will be important during testing.

**Comment by jedpittman** [comment]
For example for soc code = 11-9041.00 , the link would be: https://www.onetonline.org/link/summary/11-9041.00
Ideally we would make sure that the address could be overridden using a variable if we determined that there was another location on onet we wanted to point to instead.

**Comment by azheng1991** [comment]
Hey Jed,

I think I need to be brought up to speed on what the onet function does exactly as I'm not sure what should happen if the user is online. I have put together my initial thoughts based on what I've reviewed so far, but I'm sure what I'm doing is too straightforward since you basically laid out the steps already :) 

https://codepen.io/azheng34/pen/ExKEJQN

**Comment by jedpittman** [comment]
Allan, you're on the right track. There's two things to keep track of here:
Here are some examples of calls to the function and what it should return to give you an idea:
getOnetUrl('11-9041.00', true) => https://www.onetonline.org/link/summary/11-9041.00
getOnetUrl('11-9041.40', true) => https://www.onetonline.org/link/summary/11-9041.40
getOnetUrl('11-9041.00', false) => https://www.fakeaddress.com/11-9041.00
getOnetUrl('11-9041.50', false) => https://www.fakeaddress.com/11-9041.50

The "www.fakeaddress.com" is not important, it is just that there should be some logic that returns a garbage address but something that would change on each input making the results be different based on the input ids. 

I didn't specify it, so consider what you would return if unexpected inputs are provided or omitted. Just add a comment explaining why you chose what you did. 

The function itself is not very hard, but thinking through the cases on something that is a bit vague is the real work here.

**Comment by azheng1991** [comment]
Okay, I've given it another go, let me know if this is closer to what you're thinking: 

https://codepen.io/azheng34/pen/ExKEJQN

Basically, just added template literals for the socCode in the URL that's returned, and also added a return statement if the user wasn't online since I assumed that would mean there's no point in fetching a URL. That assumption could definitely be wrong though...

**Comment by jedpittman** [comment]
for the non-online one, I was looking for a garbage address, but it doesn't matter. The main point of the exercise was getting us both used to this process. We'll undoubtedly have to tweak the code when we get to integration. Congrats on your first item!

If you are wanting to do more before next tuesday, head into the sprint board and grab one of the issues from the top of the to do column. Then assign to yourself and move to the "in progress" and reach out to me if there's any question.

**Comment by azheng1991** [comment]
Okay great! Are you guys going to be there on Saturday as well?

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by jedpittman** [comment]
I am not.
