### ISSUE TITLE
[Volunteer Sprint] Data processing - Make sure that the data loaded into the app is complete and versioned

### ISSUE THREAD

**Issue by l-cheung** [codeforboston/jobhopper#84]
Goal: Make sure the BLS data loaded into the app is complete and versioned

There are two datasets that need to be merged together by SOC code: 
* The public BLS data available at https://www.bls.gov/oes/tables.htm
* Occupation transitions data derived from research using Burning Glass resumes: https://github.com/codeforboston/jobhopper/blob/develop/data/occupation_transitions_public_data_set.csv

The occupation transitions data is from 2010, and tells us how people transition from occupation to occupation, where each occupation is only identified by SOC code. 

BLS gives us the name of each occupation, and wage and employment information for each occupation and location, where occupations are identified by SOC code.

2019 BLS data is the sample of data currently used to build out the app. Ideally, we'd want to cover as much of the transitions data as possible by pulling employment/wage information from the latest available BLS record for each SOC code in the occupation transitions data.

It would be helpful to have people work on the following tasks:
* Determine how many of the SOC codes in the occupation transitions dataset are covered by the 2019 BLS data
* Find out what other BLS datasets we should download to increase that coverage
* Create a sustainable load process to merge relevant BLS datasets together and update the dataset if there is new data available (feel free to edit existing processes to improve efficiency)
* Make sure there are no duplicate SOC-location records, and missing values are accounted for
* Add a version/year field to each record in the table so that we know where the record came from

If editing the original load process, make sure you make the migrations consistent so that `python manage.py test` still runs after your changes.

Places to start:
* https://github.com/codeforboston/jobhopper/issues/11
* https://github.com/codeforboston/jobhopper/blob/develop/data/bls/oes_data_downloader.py
* https://github.com/codeforboston/jobhopper/blob/develop/data/scripts/sql_loader.py
* Migrations 0010 and 0011 at https://github.com/codeforboston/jobhopper/tree/develop/jobs/migrations

Guidance:
Any adhoc scripts to validate/check the data that will not run every time should be kept under data/scripts (see above sql_loader.py)
Please add any follow up work as new Issues.
Please add any additional information as needed as updates to the README.md file in the data folder.

**Comment by volunteer-a-thon** [comment]
**Summary**

See #177 

* BLS datasets include an industry classification (NAICS code). There are cases where we have multiple SOC code - location combinations due to these industries. We are only interested in wage/employment data for a given location and SOC code across all industries in the area. This is achieved by filtering the data to only have the NAICS code `000000`.

![image](https://user-images.githubusercontent.com/73145968/97645223-b7cfef00-1a22-11eb-835f-d080e8b3c3d2.png)

* BLS datasets also include wage/employment data for some counties and MSAs. However, this is likely more granular than we need. MSAs have been renamed/reclassified. We filtered to include only statewide and national data.

* To get more complete data, we pulled several years' worth of data and took the latest record for each SOC code and location.

* We added the year corresponding to each record as a field

![image](https://user-images.githubusercontent.com/73145968/97645569-ac30f800-1a23-11eb-8642-b0f5e54b4e11.png)

**Comment by jedpittman** [comment]
Lots of work has been done on this at this point and as we move further along in the project it seems clear that we have as much data in the database as we need with the exception of loading additional years. This is one that is probably something we can close at this point....but leaving open until we have the design review and stakeholder review.

**Comment by jedpittman** [comment]
Closing this; we've loaded and updated data multiple times at this point.
