### ISSUE TITLE
Landing page-results page design

### ISSUE THREAD

**Issue by edward-malouf** [codeforboston/jobhopper#99]
Incorporate job selection field, logo, and state selection field along with prompt text into the landing page and the results page.

**Comment by edward-malouf** [comment]
This might be stretching the 2 -3 hour time frame all told, but an initial design can certainly be created for discussion.

**Comment by jedpittman** [comment]
Ed, once we meet and demo tonight, Can you formulate a little bit more about what this issue will include? 

For example, at this point, I think the Figma design work is fairly complete. 

Is there anything that you think is missing in order to capture the content from Anna's requirement powerpoint or general usability? If so, let's call those things out specifically. 

What if anything could be done for the user experience to make it easier to use the application? (Should that be a separate issue perhaps with separate figma or other design elements that could eventually be added/coded?)

What if anything should we consider for different size screens? (i.e. can you think about how elements might change/need to change? Should we bail out and say that the app is only supported on full size screens? If so, what does that look like generally? A separate mockup (maybe figma) might work here?)

**Comment by edward-malouf** [comment]
Usability is the most important thing, and once the elements are pinned down then the interface must be configured to cell phone.

**Comment by jedpittman** [comment]
https://www.figma.com/file/sPliiBwA2zstfFppa2lHaC/JobHopper-Design?node-id=0%3A1
Ed demo'd this with the team on 10/13/2020 and we're closing this out.
